name: Tests

on:
  pull_request:
    branches: [master, main]

env:
  DIR: tests

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run tests
      run: python ${{ env.DIR }}/test_sdk.py
      shell: sh
